export = {
    groupPriorities: [
        {'name': 'Beacon',
            'fields': ['evn', 'e', 'aid', 'eid', 'ttm', 'dtm', 'stm', 'p', 'u', 'tid', 'tna', 'tv', ]},
        {'name': 'User',
            'fields': ['duid', 'nuid', 'tnuid', 'uid']},
        {'name': 'Session',
            'fields': ['vid', 'sid']},
        {'name': 'Transaction',
            'fields': ['tr_id', 'tr_af', 'tr_tt', 'tr_tx', 'tr_sh', 'tr_ci', 'tr_st', 'tr_co', 'tr_cu', 'ti_id', 'ti_sk', 'ti_na', 'ti_ca', 'ti_pr', 'ti_qu', 'ti_cu']},
        {'name': 'Event',
            'fields': ['se_ca', 'se_ac', 'se_la', 'se_pr', 'se_va', 'ue_pr', 'ue_px']},
        {'name': 'Page',
            'fields': ['url', 'page', 'refr', 'ds', 'cs', ]},
        {'name': 'Ad',
            'fields': ['ad_ad', 'ad_ca', 'ad_ba', 'ad_uid']},
        {'name': 'Social',
            'fields': ['sn', 'sa', 'st', 'sp']},
        {'name': 'Ping',
            'fields': ['pp_mix', 'pp_max', 'pp_miy', 'pp_may']},
        {'name': 'Context',
            'fields': ['cv', 'co', 'cx']},
        {'name': 'Browser',
            'fields': ['ua', 'fp', 'cookie', 'lang', 'vp', 'f_pdf', 'f_fla', 'f_java', 'f_ag', 'f_qt', 'f_realp', 'f_wma', 'f_dir', 'f_gears']},
        {'name': 'Device',
            'fields': ['tz', 'ip', 'mac', 'res', 'ctype', 'cd', ]}
    ],
    paramMap: {
        'tna':{'name': 'Tracker Name', 'type': 'text'},
        'evn':{'name': 'Event Vendor', 'type': 'text', 'deprecated': true},
        'aid':{'name': 'Application ID', 'type': 'text'},
        'p':{'name': 'Platform', 'type': 'enum', 'values': ['web', 'mob', 'pc', 'srv', 'app', 'tv', 'cnsl', 'iot']},
        'dtm':{'name': 'Device Created Timestamp', 'type': 'epoc'},
        'stm':{'name': 'Device Sent Timestamp', 'type': 'epoc'},
        'ttm':{'name': 'True Timestamp', 'type': 'epoc'},
        'tz':{'name': 'Client Timezone', 'type': 'text'},
        'e':{'name': 'Event Type', 'type': 'emap', 'values': {'pv': 'Pageview', 'pp': 'Page Ping', 'ue': 'Unstructured Event', 'tr': 'Transaction', 'ti': 'Transaction Item', 'se': 'Structured Event'}},
        'tid':{'name': 'Transaction ID', 'type': 'numb', 'deprecated': true},
        'eid':{'name': 'Event ID', 'type': 'uuid'},
        'tv':{'name': 'Tracker Version', 'type': 'text'},
        'duid':{'name': 'Domain User ID', 'type': 'text'},
        'nuid':{'name': 'Network User ID', 'type': 'uuid', 'cookie': 'sp'},
        'tnuid':{'name': 'Network User ID (override)', 'type': 'uuid'},
        'uid':{'name': 'Client User ID', 'type': 'text'},
        'vid':{'name': 'Domain Session Index', 'type': 'numb'},
        'sid':{'name': 'Domain Session ID', 'type': 'uuid'},
        'ip':{'name': 'User IP Address', 'type': 'text'},
        'res':{'name': 'Device Resolution', 'type': 'text'},
        'url':{'name': 'Page URL', 'type': 'text'},
        'ua':{'name': 'Browser User Agent', 'type': 'text', 'header': 'User-Agent'},
        'page':{'name': 'Page Title', 'type': 'text'},
        'refr':{'name': 'Page Referrer URL', 'type': 'text'},
        'fp':{'name': 'Browser Fingerprint', 'type': 'text'},
        'ctype':{'name': 'Connection Type', 'type': 'text'},
        'cookie':{'name': 'Cookies Allowed', 'type': 'bool'},
        'lang':{'name': 'Browser Language', 'type': 'text', 'header': 'Accept-Language'},
        'f_pdf':{'name': 'PDF Support', 'type': 'bool'},
        'f_qt':{'name': 'QuickTime Support', 'type': 'bool'},
        'f_realp':{'name': 'RealPlayer Support', 'type': 'bool'},
        'f_wma':{'name': 'Windows Media Player Support', 'type': 'bool'},
        'f_dir':{'name': 'Director Support', 'type': 'bool'},
        'f_fla':{'name': 'Flash Support', 'type': 'bool'},
        'f_java':{'name': 'Java Support', 'type': 'bool'},
        'f_gears':{'name': 'Google Gears Support', 'type': 'bool'},
        'f_ag':{'name': 'Silverlight Support', 'type': 'bool'},
        'cd':{'name': 'Screen Colour Depth', 'type': 'text'},
        'ds':{'name': 'Document Size (pixels)', 'type': 'text'},
        'cs':{'name': 'Document Character Set', 'type': 'text'},
        'vp':{'name': 'Viewport Size', 'type': 'text'},
        'mac':{'name': 'MAC address', 'type': 'text'},
        'pp_mix':{'name': 'Minimum Horizontal Offset', 'type': 'numb'},
        'pp_max':{'name': 'Maximum Horizontal Offset', 'type': 'numb'},
        'pp_miy':{'name': 'Minimum Vertical Offset', 'type': 'numb'},
        'pp_may':{'name': 'Maximum Vertical Offset', 'type': 'numb'},
        'ad_ba':{'name': 'Banner ID', 'type': 'text'},
        'ad_ca':{'name': 'Campaign ID', 'type': 'text'},
        'ad_ad':{'name': 'Advertiser ID', 'type': 'text'},
        'ad_uid':{'name': 'User ID', 'type': 'text'},
        'tr_id':{'name': 'Transaction ID', 'type': 'text'},
        'tr_af':{'name': 'Transaction Affiliation', 'type': 'text'},
        'tr_tt':{'name': 'Transaction Total', 'type': 'doub'},
        'tr_tx':{'name': 'Transaction Tax', 'type': 'doub'},
        'tr_sh':{'name': 'Transaction Shipping', 'type': 'doub'},
        'tr_ci':{'name': 'Transaction City', 'type': 'text'},
        'tr_st':{'name': 'Transaction State', 'type': 'text'},
        'tr_co':{'name': 'Transaction Country', 'type': 'text'},
        'tr_cu':{'name': 'Transaction Currency', 'type': 'text'},
        'ti_id':{'name': 'Item Transaction ID', 'type': 'text'},
        'ti_sk':{'name': 'Item SKU', 'type': 'text'},
        'ti_na':{'name': 'Item Name', 'type': 'text'},
        'ti_ca':{'name': 'Item Category', 'type': 'text'},
        'ti_pr':{'name': 'Item Price', 'type': 'doub'},
        'ti_qu':{'name': 'Item Quantity', 'type': 'numb'},
        'ti_cu':{'name': 'Item Currency', 'type': 'text'},
        'sa':{'name': 'Social Action', 'type': 'text'},
        'sn':{'name': 'Social Network', 'type': 'text'},
        'st':{'name': 'Social Target', 'type': 'text'},
        'sp':{'name': 'Social Pagepath', 'type': 'text'},
        'se_ca':{'name': 'Event Category', 'type': 'text'},
        'se_ac':{'name': 'Event Action', 'type': 'text'},
        'se_la':{'name': 'Event Label', 'type': 'text'},
        'se_pr':{'name': 'Event Property', 'type': 'text'},
        'se_va':{'name': 'Event Value', 'type': 'doub'},
        'ue_pr':{'name': 'Unstructured Event', 'type': 'json'},
        'ue_px':{'name': 'Unstructured Event', 'type': 'ba64', 'then': 'json'},
        'cv':{'name': 'Context Vendor', 'type': 'text', 'deprecated': true},
        'co':{'name': 'Custom Context', 'type': 'json'},
        'cx':{'name': 'Custom Context', 'type': 'ba64', 'then': 'json'},
        'u':{'name': 'Redirect To', 'type': 'text'}
    }
};
